server:
  port: 8080

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false #是否把自己注册到eureka
    fetch-registry: false #是否拉去其他服务的信息。
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
