server:
  port: 10000

spring:
  application:
    name: consumer-server
  cloud:
    loadbalancer:
      retry:
        enabled: true

user-server:
  ribbon:
    ConnectTimeout: 250 #Ribbon 超时时间
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true #是否所有操作都可以重试
    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
    MaxAutoRetries: 1 #当前实例重试次数

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #调用getHostname 返回ip 而不是hostname
    ip-address: 127.0.0.1 #指定自己的ip，不指定会自己寻找。
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  eureka:
    enabled: true