server:
  port: 10086

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否把自己注册到eureka
    fetch-registry: false #是否拉去其他服务的信息。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
#    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）